### ISSUE TITLE
Move pieces of constructor to parent

### ISSUE THREAD

**Issue by GregTheGreek** [ansermino/fixed-sized-numbers-ts#1]
Lines 43-53 from `UnsignedNumber.ts` should probably be moved into the parent class. 
```
        // TODO: consider moving into parent class
        super()
        if ((typeof value === "number")) {
            // TODO: Validate for size
            this._value = new BigNumber(value)
        } else if (value instanceof BigNumber) {
            this._value = value
        } else if (!value) {
            this._value = new BigNumber(0)
        } else {
            throw new TypeNotSupportedError()
        }
```
Rational: Both signed and unsigned integers will benefit from those meet all the above checks.
`size > 0` does not qualify since signed may be negative.

**Comment by ansermino** [comment]
Introduced a MetaInteger class in `lib/MetaInteger.ts`. Right now the constructor is in the subclasses, but once we have a better idea of the conditions we need to check all types for we should migrate them up.
